version: '3'
services:
    gatsby:
        image: mcr.microsoft.com/devcontainers/typescript-node
        volumes:
            - .:/workspace:cached
        command: sleep infinity
        links:
            - php-build
    php-build:
        dockerfile: DockerfilePHP
        volumes:
            - .:/workspace:cached
        command: sleep infinity