/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as IcalRouteImport } from './routes/ical'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TideTablesIndexRouteImport } from './routes/tide-tables/index'
import { Route as TideTablesSplatRouteImport } from './routes/tide-tables/$'
import { Route as TideGraphDateRouteImport } from './routes/tide-graph/$date'

const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const IcalRoute = IcalRouteImport.update({
  id: '/ical',
  path: '/ical',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TideTablesIndexRoute = TideTablesIndexRouteImport.update({
  id: '/tide-tables/',
  path: '/tide-tables/',
  getParentRoute: () => rootRouteImport,
} as any)
const TideTablesSplatRoute = TideTablesSplatRouteImport.update({
  id: '/tide-tables/$',
  path: '/tide-tables/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TideGraphDateRoute = TideGraphDateRouteImport.update({
  id: '/tide-graph/$date',
  path: '/tide-graph/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ical': typeof IcalRoute
  '/sitemap': typeof SitemapRoute
  '/tide-graph/$date': typeof TideGraphDateRoute
  '/tide-tables/$': typeof TideTablesSplatRoute
  '/tide-tables': typeof TideTablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ical': typeof IcalRoute
  '/sitemap': typeof SitemapRoute
  '/tide-graph/$date': typeof TideGraphDateRoute
  '/tide-tables/$': typeof TideTablesSplatRoute
  '/tide-tables': typeof TideTablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ical': typeof IcalRoute
  '/sitemap': typeof SitemapRoute
  '/tide-graph/$date': typeof TideGraphDateRoute
  '/tide-tables/$': typeof TideTablesSplatRoute
  '/tide-tables/': typeof TideTablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ical'
    | '/sitemap'
    | '/tide-graph/$date'
    | '/tide-tables/$'
    | '/tide-tables'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ical'
    | '/sitemap'
    | '/tide-graph/$date'
    | '/tide-tables/$'
    | '/tide-tables'
  id:
    | '__root__'
    | '/'
    | '/ical'
    | '/sitemap'
    | '/tide-graph/$date'
    | '/tide-tables/$'
    | '/tide-tables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IcalRoute: typeof IcalRoute
  SitemapRoute: typeof SitemapRoute
  TideGraphDateRoute: typeof TideGraphDateRoute
  TideTablesSplatRoute: typeof TideTablesSplatRoute
  TideTablesIndexRoute: typeof TideTablesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ical': {
      id: '/ical'
      path: '/ical'
      fullPath: '/ical'
      preLoaderRoute: typeof IcalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tide-tables/': {
      id: '/tide-tables/'
      path: '/tide-tables'
      fullPath: '/tide-tables'
      preLoaderRoute: typeof TideTablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tide-tables/$': {
      id: '/tide-tables/$'
      path: '/tide-tables/$'
      fullPath: '/tide-tables/$'
      preLoaderRoute: typeof TideTablesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tide-graph/$date': {
      id: '/tide-graph/$date'
      path: '/tide-graph/$date'
      fullPath: '/tide-graph/$date'
      preLoaderRoute: typeof TideGraphDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IcalRoute: IcalRoute,
  SitemapRoute: SitemapRoute,
  TideGraphDateRoute: TideGraphDateRoute,
  TideTablesSplatRoute: TideTablesSplatRoute,
  TideTablesIndexRoute: TideTablesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
